version: 2
updates:
  # Maintain dependencies for go-modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "monthly"
