linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - cyclop
    - durationcheck
    - errname
    - errorlint
    - exportloopref
    - goimports
    - gocritic
    - gosec

linters-settings:
  cyclop:
    max-complexity: 18
  gocritic:
    disabled-checks:
      - singleCaseSwitch
  staticcheck:
    checks:
      - all
      - '-SA1019' # TODO

issues:
  exclude-rules:
    - path: "."
      linters:
        - typecheck


