name: aws-scan
repository: github.com/aquasecurity/trivy-aws
maintainer: aquasecurity
summary: Trivy AWS Cloud scanning plugin
version: "0.10.0"
usage: AWS Trivy plugin
description: |-
  Trivy AWS plugin for the Trivy security scanner
  https://github.com/aquasecurity/trivy-aws
platforms:
  - uri: https://github.com/aquasecurity/trivy-aws/releases/download/v0.10.0/trivy-aws.tar.gz
    bin: ./trivy-aws