name: aws-scan
repository: github.com/aquasecurity/trivy-aws
maintainer: aquasecurity
summary: Trivy AWS Cloud scanning plugin
version: "0.1.0"
usage: AWS Trivy plugin
description: |-
  Trivy AWS plugin for the Trivy security scanner
  https://github.com/aquasecurity/trivy-aws
platforms:
  - uri: https://github.com/aquasecurity/trivy-aws/archive/refs/tags/v0.9.0.tar.gz
    bin: ./trivy-aws
