name: trivy-aws
repository: github.com/aquasecurity/trivy-aws
version: "0.1.0"
usage: AWS Trivy plugin
description: |-
  Trivy AWS plugin for the Trivy security scanner
  https://github.com/aquasecurity/trivy-aws
platforms:
  - uri: .\trivy-aws.exe
    bin: .\trivy-aws.exe