name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

env:
  GO_VERSION: '1.22'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: make build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            trivy-aws-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}