name: test go

on:
  pull_request:
  merge_group:
  schedule:
  - cron:  0 23 * * *

env:
  GO_VERSION: '1.22'

jobs:
  build:
    name: building defsec
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: go mod tidy
      if: matrix.os == 'ubuntu-latest'
      run: |
        go mod tidy
        if [ -n "$(git status --porcelain)" ]; then
          echo "Run 'go mod tidy' and push it"
          exit 1
        fi

    - name: Run non-localstack tests
      if: matrix.os != 'ubuntu-latest'
      run: make test-no-localstack
      shell: bash
    - name: Run full tests
      if: matrix.os == 'ubuntu-latest'
      run: make test
      shell: bash
